In [399]:
import numpy as np
practice_array_1 = np.array([1,3,5,7,9])
practice_array_2 = np.array([2,4,6,8,10])
practice_array_1[4] = 11
copy_array_1 = practice_array_1.copy()
view_array_1 = copy_array_1.view()

practice_array_1

array([ 1,  3,  5,  7, 11])

In [400]:
copy_array_1

array([ 1,  3,  5,  7, 11])

In [401]:
view_array_1

array([ 1,  3,  5,  7, 11])

In [402]:
view_array_1[2] = 2
copy_array_1

array([ 1,  3,  2,  7, 11])

In [403]:
view_array_1

array([ 1,  3,  2,  7, 11])

In [404]:
practice_array_1

array([ 1,  3,  5,  7, 11])

In [405]:
# gives the dimensions of the array and not the size
practice_array_2 = np.concatenate([practice_array_2,[12]])
practice_array_2.shape

(6,)

In [406]:
# reshapes to the dimensions given as arguments for reshape function
# practice_array_2.reshape(1,2)

In [407]:
concat_array1 = practice_array_2.reshape(2,3)

In [408]:
concat_array2 = practice_array_2.reshape(1,6)

In [409]:
practice_array_2.reshape(2,1,3)

array([[[ 2,  4,  6]],

       [[ 8, 10, 12]]])

In [410]:
practice_array_2.reshape(2,3,1)

array([[[ 2],
        [ 4],
        [ 6]],

       [[ 8],
        [10],
        [12]]])

In [411]:
practice_array_2.reshape(1,1,1,1,3,2)

array([[[[[[ 2,  4],
           [ 6,  8],
           [10, 12]]]]]])

In [412]:
practice_array_2.reshape(1,1,2,1,3,1)

array([[[[[[ 2],
           [ 4],
           [ 6]]],


         [[[ 8],
           [10],
           [12]]]]]])

In [413]:
# np.concatenate([concat_array1, concat_array2])
# np.array(1,2,3)
concat_array2 = concat_array2.reshape(2,3)
concat_array2 = np.array([1,2,3,4,5,6]).reshape(2,3)
concat_array2

array([[1, 2, 3],
       [4, 5, 6]])

In [414]:

np.concatenate([concat_array1, concat_array2])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [415]:
np.concatenate([concat_array1, concat_array2], axis=0)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [416]:
np.concatenate([concat_array1, concat_array2], axis=1)

array([[ 2,  4,  6,  1,  2,  3],
       [ 8, 10, 12,  4,  5,  6]])

In [417]:
three_concat_1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(2,3,2)
print(three_concat_1)
three_concat_2 = np.array([2,4,6,8,10,12,14,16,18,20,22,24]).reshape(2,3,2)
print(three_concat_2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]]


In [418]:
axis0 = np.concatenate([three_concat_1, three_concat_2], axis=0)
print(axis0)
print(axis0.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]]
(4, 3, 2)


In [419]:
axis1 = np.concatenate([three_concat_1, three_concat_2], axis=1)
print(axis1)
print(axis1.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 2  4]
  [ 6  8]
  [10 12]]

 [[ 7  8]
  [ 9 10]
  [11 12]
  [14 16]
  [18 20]
  [22 24]]]
(2, 6, 2)


In [420]:
axis2 = np.concatenate([three_concat_1, three_concat_2], axis=2)
print(axis2)
print(axis2.ndim)
print(axis2.shape)

[[[ 1  2  2  4]
  [ 3  4  6  8]
  [ 5  6 10 12]]

 [[ 7  8 14 16]
  [ 9 10 18 20]
  [11 12 22 24]]]
3
(2, 3, 4)


In [421]:
# np.concatenate([three_concat_1, three_concat_2], axis=3)