In [137]:
import numpy as np
import pandas as pd

In [138]:
# numpy 1d array
np_array = np.array([1,2,3,4,5])
print(np_array)
np_array

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [139]:
# numpy 1d array
np_2d_array = np.array([[2,4,6],[1,3,5]])
print(type(np_array), type(np_2d_array))
np_2d_array

# both array type is numpy.ndarray
# no indexing is mentioned and no custom indexing available

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


array([[2, 4, 6],
       [1, 3, 5]])

In [140]:
# both are 1 d array only
print(pd.Series([5,10,15],index=['a','b','c'])) 
print(pd.Series([[2,4,6],[1,3,5]],index=['a','b']))
print(pd.Series([(2,4,6),(1,3,5)],index=['c','d']))

a     5
b    10
c    15
dtype: int64
a    [2, 4, 6]
b    [1, 3, 5]
dtype: object
c    (2, 4, 6)
d    (1, 3, 5)
dtype: object


In [141]:
pd.DataFrame([[2,4,6],[1,3,5]])

0  1  2
0  2  4  6
1  1  3  5

In [142]:
series_1 = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
series_2 = pd.Series([6,7,8,9,10],index=['a','b','c','d','e'])
dicti = {
    # keys are column values in dictionary
    'f' : series_1,
    'g' : series_2
}
dict_df = pd.DataFrame(dicti)
print(dict_df)
pd.DataFrame([series_1,series_2])


   f   g
a  1   6
b  2   7
c  3   8
d  4   9
e  5  10


a  b  c  d   e
0  1  2  3  4   5
1  6  7  8  9  10

In [143]:
print(dict_df['f']['b'])
dict_df['f']['b'] = 5
# dict_df['h']['i'] = 6 # gives error not allowing addition of records
dict_df.loc['e','h'] = 6 # does not give error allows addition of values
print(dict_df)

2
   f   g    h
a  1   6  NaN
b  5   7  NaN
c  3   8  NaN
d  4   9  NaN
e  5  10  6.0


C:\Users\Palanimohan\AppData\Local\Temp\ipykernel_30792\2203162847.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dict_df['f']['b'] = 5
